## Numpy
- 파이썬에서 수학적 계산을 쉽게 할 수 있도록 도와주는 라이브러리

In [1]:
import numpy as np

In [2]:
array = np.array(['A','B','C','D','E'])
array

array(['A', 'B', 'C', 'D', 'E'], dtype='<U1')

In [5]:
print(array.shape)
print(array.ndim)
print(array.dtype)

(5,)
1
<U1


In [6]:
array2 = np.array([["A",'B', "C"], ["D","E","F"]])
print(array2)

[['A' 'B' 'C']
 ['D' 'E' 'F']]


In [7]:
print(array2.shape)
print(array2.ndim)
print(array2.dtype)

(2, 3)
2
<U1


In [8]:
x = np.array([[[1,1,2], [2,3,3]], [[1,1,1], [1,1,1]]])
print(x.shape)
print(x)

(2, 2, 3)
[[[1 1 2]
  [2 3 3]]

 [[1 1 1]
  [1 1 1]]]


In [13]:
array4 = np.array(['1','2','3','4','5'])

print(array4.dtype)

array4 = array4.astype(np.float64)

print(array4.dtype)

<U1
float64


In [14]:
arr = np.arange(1,10)

In [15]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[0:3]

array([1, 2, 3])

In [17]:
arr[arr > 6]

array([7, 8, 9])

In [ ]:
arr1 = 